; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32@6.10.0
framework = espidf
lib_extra_dirs = lib
lib_deps = baracodadailyhealthtech/cJSON@^1.7.18
extra_scripts = pre:scripts/generate_web.py

[env:esp32-c3-devkitm-1]
extends = common
board = esp32-c3-devkitm-1

[env:esp32-c3-supermini-2MB]
extends = common
board = esp32-c3-devkitm-1
board_upload.flash_size = 2MB
board_build.flash_size = 2MB
board_build.partitions = partitions_2M.csv